---
# tasks file for task_scheduler

- name: 'include tasks scheduler'
  include_tasks: 'task_scheduler.yml'
  loop: "{{ scheduled_tasks }}"
  loop_control:
    loop_var: scheduled_task
  tags:
    - task_scheduler
    - configuration
