---
# tasks file for task_scheduler
- name: "Create {{ scheduled_task.name }} scheduled task"
  win_scheduled_task:
    name: "{{ scheduled_task.name }}"
    description: "{{ scheduled_task.description | default(omit) }}"
    actions: "{{ scheduled_task.actions|default(omit) }}"
    allow_demand_start: "{{ scheduled_task.allow_demand_start | default(omit) }}"
    allow_hard_terminate: "{{ scheduled_task.allow_hard_terminate | default(omit) }}"
    author: "{{ scheduled_task.author | default(omit) }}"
    compatibility: "{{ scheduled_task.compatibility | default(omit) }}"
    date: "{{ scheduled_task.date | default(omit) }}"
    delete_expired_task_after: "{{ scheduled_task.delete_expired_task_after | default(omit) }}"
    disallow_start_if_on_batteries: "{{ scheduled_task.disallow_start_if_on_batteries | default(omit) }}"
    display_name: "{{ scheduled_task.display_name | default(omit) }}"
    enabled: "{{ scheduled_task.enabled | default(omit) }}"
    execution_time_limit: "{{ scheduled_task.execution_time_limit | default(omit) }}"
    group: "{{ scheduled_task.group | default(omit) }}"
    hidden: "{{ scheduled_task.delete_expired_task_after | default(omit) }}"
    logon_type: "{{ scheduled_task.logon_type | default(omit) }}"
    multiple_instances: "{{ scheduled_task.multiple_instances | default(omit) }}"
    password: "{{ scheduled_task.password| default(omit) }}"
    path: "{{ scheduled_task.path | default(omit) }}"
    priority: "{{ scheduled_task.priority | default(omit) }}"
    restart_count: "{{ scheduled_task.restart_count | default(omit) }}"
    run_level: "{{ scheduled_task.run_level | default(omit) }}"
    run_only_if_idle: "{{ scheduled_task.run_only_if_idle | default(omit) }}"
    run_only_if_network_available: "{{ scheduled_task.run_only_if_network_available | default(omit) }}"
    source: "{{ scheduled_task.source | default(omit) }}"
    start_when_available: "{{ scheduled_task.start_when_available | default(omit) }}"
    state: "{{ scheduled_task.state | default(omit)  }}"
    stop_if_going_on_batteries: "{{ scheduled_task.stop_if_going_on_batteries | default(omit) }}"
    triggers: "{{ scheduled_task.triggers | default(omit) }}"
    update_password: "{{ scheduled_task.update_password | default(omit) }}"
    username: "{{ scheduled_task.username | default(omit) }}"
    version: "{{ scheduled_task.version | default(omit) }}"
    wake_to_run: "{{ scheduled_task.wake_to_run | default(omit) }}"
  register: schedtaskout

- debug: var=schedtaskout

- name: Capture results of {{ scheduled_task.name }}
  include_role:
    name: capture_output
  vars:
    new_item: "{{inventory_hostname}},{{ansible_ip_addresses|first}},{{ansible_os_name}},{{'create or modify ' if scheduled_task.state == 'present' else 'delete '}} {{scheduled_task.name}}, {{(schedtaskout.failed == false) | ternary ((schedtaskout.changed == true)| ternary( scheduled_task.name +' scheduled task has been '+ ('created or modified ' if scheduled_task.state == 'present' else 'deleted ') + 'successfully',scheduled_task.name +' is already exists'  ),('creation or updation ' if scheduled_task.state == 'present' else 'deletion ')+'of scheduled_task.name got failed. This may due to multiple reasons')}}"
  when: schedtaskout is defined